from __future__ import annotations

from dataclasses import dataclass
import math
from typing import Any, Literal, Sequence

from .planner import FoodLike, PlannedRecipe, RecipeSpec, plan_recipe


OptimizerEngine = Literal["or-tools-cp-sat", "deterministic-greedy"]

_CP_MODEL: Any | None = None
_CP_MODEL_LOAD_FAILED = False


def warm_up_cp_sat() -> bool:
    """Load the CP-SAT module before the API reports readiness.

    Importing OR-Tools can be expensive on a fresh Python process. Keeping the
    import behind this small seam preserves the deterministic fallback for a
    partial deployment, while the application lifespan can pay the one-time
    cost before the first user request.
    """

    global _CP_MODEL, _CP_MODEL_LOAD_FAILED
    if _CP_MODEL is not None:
        return True
    if _CP_MODEL_LOAD_FAILED:
        return False
    try:
        from ortools.sat.python import cp_model
    except Exception:
        _CP_MODEL_LOAD_FAILED = True
        return False
    _CP_MODEL = cp_model
    return True


@dataclass(frozen=True)
class MultiDayPlanResult:
    """A schedule of already materialized recipe plans.

    The optimizer only chooses between plans produced by the existing
    deterministic ingredient matcher. It never invents an ingredient,
    converts an unsafe package unit, or mutates inventory. That keeps the
    solver as a selection module rather than a second source of inventory
    truth.
    """

    plans: tuple[PlannedRecipe, ...]
    engine: OptimizerEngine
    fallback_reason: str | None = None


@dataclass(frozen=True)
class _WorkingFood:
    id: str
    canonical_name: str
    priority: int
    quantity: float
    unit: str


def optimize_multi_day_plans(
    foods: Sequence[FoodLike],
    max_minutes: int,
    *,
    specs: Sequence[RecipeSpec],
    avoid_allergens: set[str] | frozenset[str] | None = None,
    day_count: int = 3,
    servings: int = 1,
) -> MultiDayPlanResult:
    """Choose up to ``day_count`` distinct plans under shared lot capacity.

    Each candidate is first generated by :func:`plan_recipe` against the
    original inventory. CP-SAT then chooses a globally compatible subset. A
    candidate's allocations are expressed in the source lot's unit, so the
    inventory capacity constraint is applied in exactly the same unit that
    the later consume event uses.

    OR-Tools is a production dependency, but the deterministic greedy path is
    kept as a deliberate recovery seam for a partially deployed version or a
    solver failure. The fallback has the same contract as the former API
    implementation: subtract selected allocations before calculating the next
    day and never create stock for a missing ingredient.
    """

    if day_count < 1:
        return MultiDayPlanResult((), "deterministic-greedy", "day_count must be positive")
    if not foods:
        return MultiDayPlanResult((), "deterministic-greedy", "inventory is empty")

    base_foods = tuple(_as_planner_food(food) for food in foods)
    recipes = tuple(specs)
    candidates = _candidate_plans(base_foods, max_minutes, recipes, avoid_allergens, servings)
    if not candidates:
        return MultiDayPlanResult((), "deterministic-greedy", "no recipe candidate matched the inventory")

    selected = _solve_with_cp_sat(base_foods, candidates, day_count)
    if selected is not None:
        # Re-materialize the chosen recipe IDs in day order against the
        # remaining lots. The CP-SAT capacity proof is still based on the
        # original candidate allocations, while the response now exposes the
        # same day-specific availability that completion will consume.
        materialized = _materialize_selected_schedule(
            base_foods,
            max_minutes,
            recipes,
            avoid_allergens,
            selected,
            servings,
        )
        if materialized is not None:
            return MultiDayPlanResult(tuple(materialized), "or-tools-cp-sat")
        fallback_reason = "선택된 후보를 날짜별 남은 lot에 다시 배치하지 못했습니다."
    else:
        fallback_reason = "OR-Tools가 일정을 계산하지 못했습니다."

    greedy = _greedy_multi_day(base_foods, max_minutes, recipes, avoid_allergens, day_count, servings)
    return MultiDayPlanResult(
        tuple(greedy),
        "deterministic-greedy",
        f"{fallback_reason} 결정론적 fallback을 사용했습니다.",
    )


def _candidate_plans(
    foods: Sequence[FoodLike],
    max_minutes: int,
    specs: Sequence[RecipeSpec],
    avoid_allergens: set[str] | frozenset[str] | None,
    servings: int,
) -> tuple[PlannedRecipe, ...]:
    candidates: list[PlannedRecipe] = []
    seen: set[str] = set()
    for spec in specs:
        if spec.id in seen:
            continue
        candidate = plan_recipe(
            list(foods),
            max_minutes,
            specs=tuple(specs),
            preferred_recipe_id=spec.id,
            avoid_allergens=avoid_allergens,
            servings=servings,
        )
        if candidate is not None:
            candidates.append(candidate)
            seen.add(candidate.recipe_id)
    return tuple(candidates)


def _solve_with_cp_sat(
    foods: Sequence[FoodLike],
    candidates: Sequence[PlannedRecipe],
    day_count: int,
) -> list[PlannedRecipe] | None:
    if not warm_up_cp_sat():
        return None
    cp_model = _CP_MODEL

    model = cp_model.CpModel()
    selection: dict[tuple[int, int], object] = {}
    day_active: list[object] = []

    for day_index in range(day_count):
        active = model.NewBoolVar(f"day_{day_index + 1}_active")
        day_active.append(active)
        variables = []
        for candidate_index, candidate in enumerate(candidates):
            variable = model.NewBoolVar(f"day_{day_index + 1}_recipe_{candidate_index}")
            selection[(day_index, candidate_index)] = variable
            variables.append(variable)
        model.Add(sum(variables) == active)

    # A saved 3-day preview is a contiguous schedule. An empty day may only
    # appear after the last selected day, never between two selected days.
    for day_index in range(day_count - 1):
        model.Add(day_active[day_index] >= day_active[day_index + 1])

    for candidate_index, candidate in enumerate(candidates):
        model.Add(
            sum(selection[(day_index, candidate_index)] for day_index in range(day_count)) <= 1
        )

    capacities = {
        food.id: _scaled_quantity(getattr(food, "quantity", 0))
        for food in foods
    }
    usage_by_food: dict[str, dict[int, int]] = {food_id: {} for food_id in capacities}
    for candidate_index, candidate in enumerate(candidates):
        for food_id, quantity in _candidate_usage(candidate).items():
            if food_id in capacities:
                usage_by_food[food_id][candidate_index] = _scaled_quantity(quantity)

    for food_id, capacity in capacities.items():
        terms = [
            usage * selection[(day_index, candidate_index)]
            for candidate_index, usage in usage_by_food[food_id].items()
            for day_index in range(day_count)
        ]
        model.Add(sum(terms) <= capacity)

    # A full schedule is more useful than a high-scoring single dish. Once
    # the number of days is tied, the existing Rescue score and matched ratio
    # decide the candidate. All coefficients are integers as required by
    # CP-SAT, and the final terms are deterministic tie-breakers.
    objective_terms = []
    for day_index in range(day_count):
        day_bonus = (day_count - day_index) * 10
        for candidate_index, candidate in enumerate(candidates):
            coefficient = (
                1_000_000
                + int(round(candidate.score * 100))
                + int(round(candidate.matched_ratio * 100))
                + day_bonus
            )
            objective_terms.append(coefficient * selection[(day_index, candidate_index)])
    model.Maximize(sum(objective_terms))

    solver = cp_model.CpSolver()
    solver.parameters.max_time_in_seconds = 0.75
    solver.parameters.num_search_workers = 1
    solver.parameters.random_seed = 0
    result = solver.Solve(model)
    if result not in (cp_model.OPTIMAL, cp_model.FEASIBLE):
        return None

    chosen: list[PlannedRecipe] = []
    for day_index in range(day_count):
        selected_for_day = [
            candidates[candidate_index]
            for candidate_index in range(len(candidates))
            if solver.Value(selection[(day_index, candidate_index)])
        ]
        if not selected_for_day:
            break
        chosen.append(selected_for_day[0])
    return chosen or None


def _materialize_selected_schedule(
    foods: Sequence[FoodLike],
    max_minutes: int,
    specs: Sequence[RecipeSpec],
    avoid_allergens: set[str] | frozenset[str] | None,
    selected: Sequence[PlannedRecipe],
    servings: int,
) -> list[PlannedRecipe] | None:
    """Rebuild selected days so availability reflects earlier allocations."""

    working = list(foods)
    plans: list[PlannedRecipe] = []
    for candidate in selected:
        plan = plan_recipe(
            working,
            max_minutes,
            specs=tuple(specs),
            preferred_recipe_id=candidate.recipe_id,
            avoid_allergens=avoid_allergens,
            servings=servings,
        )
        if plan is None or plan.recipe_id != candidate.recipe_id:
            return None
        plans.append(plan)
        working = _remaining_foods(working, plan)
    return plans


def _greedy_multi_day(
    foods: Sequence[FoodLike],
    max_minutes: int,
    specs: Sequence[RecipeSpec],
    avoid_allergens: set[str] | frozenset[str] | None,
    day_count: int,
    servings: int,
) -> list[PlannedRecipe]:
    working = list(foods)
    excluded: set[str] = set()
    plans: list[PlannedRecipe] = []
    for _ in range(day_count):
        plan = plan_recipe(
            working,
            max_minutes,
            specs=tuple(specs),
            exclude_recipe_ids=excluded,
            avoid_allergens=avoid_allergens,
            servings=servings,
        )
        if plan is None:
            break
        plans.append(plan)
        excluded.add(plan.recipe_id)
        working = _remaining_foods(working, plan)
        if not working:
            break
    return plans


def _remaining_foods(foods: Sequence[FoodLike], plan: PlannedRecipe) -> list[_WorkingFood]:
    consumed_by_food_id: dict[str, float] = {}
    for ingredient in plan.ingredients:
        for allocation in ingredient.allocations:
            consumed_by_food_id[allocation.food_id] = round(
                consumed_by_food_id.get(allocation.food_id, 0) + allocation.quantity,
                3,
            )
    return [
        food
        for food in (
            _with_quantity(food, round(food.quantity - consumed_by_food_id.get(food.id, 0), 3))
            for food in foods
        )
        if food.quantity > 1e-9
    ]


def _candidate_usage(plan: PlannedRecipe) -> dict[str, float]:
    usage: dict[str, float] = {}
    for ingredient in plan.ingredients:
        for allocation in ingredient.allocations:
            usage[allocation.food_id] = round(
                usage.get(allocation.food_id, 0) + allocation.quantity,
                3,
            )
    return usage


def _as_planner_food(food: FoodLike) -> _WorkingFood:
    return _WorkingFood(
        id=str(food.id),
        canonical_name=str(food.canonical_name),
        priority=int(food.priority),
        quantity=float(food.quantity),
        unit=str(food.unit),
    )


def _with_quantity(food: FoodLike, quantity: float) -> _WorkingFood:
    return _WorkingFood(
        id=food.id,
        canonical_name=food.canonical_name,
        priority=food.priority,
        quantity=quantity,
        unit=food.unit,
    )


def _scaled_quantity(value: float) -> int:
    try:
        numeric = float(value)
    except (TypeError, ValueError):
        return 0
    if not math.isfinite(numeric) or numeric <= 0:
        return 0
    return int(round(numeric * 1000))
